### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Dhruvesh16** [ProjectBlaze/maintainership#1]
## Device you want to apply for
```
Your device name and codename
```
Realme XT (RMX1921)
## Device tree sources

```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```
https://github.com/Dhruvesh16/device_realme_RMX1921.git
https://gitlab.com/Dhruvesh16/vendor_realme_RMX1921.git
https://github.com/Dhruvesh16/android_kernel_realme_RMX1921.git
## Link to the platform where you have released your unofficial build
```
Insert here


## Other ROM's you maintain officially or unofficially
```
Insert here
```
Official:Spark,PPUI
## Bugs on unofficial build
```
None
```

## How long have you been building for?
3 months
Weeks/Months/Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Your Telegram username
```
@dhruvesh_23

**Comment by BasharatKar** [comment]
Is everything fine in ur build anything broken?

**Comment by Dhruvesh16** [comment]
Everything fine 

> Is everything fine in ur build anything broken?

**Comment by thefaizanbashir** [comment]
You're accepted. Welcome to ProjectBlaze.

**Comment by BasharatKar** [comment]
@thefaizanbashir Wah bete

**Comment by thefaizanbashir** [comment]
Your trees are fine. Your commit history is descent. You're accepted, welcome to ProjectBlaze. @TechnoStartOfficial & @anupam41 @BasharatKar kindly get in touch

**Comment by Dhruvesh16** [comment]
> Your trees are fine. Your commit history is descent. You're accepted, welcome to ProjectBlaze. @TechnoStartOfficial & @anupam41 @BasharatKar kindly get in touch
Thank you

**Comment by anupam41** [comment]
@Dhruvesh16 This device have under display fingerprint scanner😭
