### ISSUE TITLE
Bayerische Motoren Werke

### ISSUE THREAD

**Issue by BayerischeMotorenWerke** [ProjectBlaze/maintainership#10]
## Device you want to apply for
```
Your device name and codename
```

## Device tree sources

```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Weeks/Months/Years
```

## SELinux status?
```
Enforcing.
```yes

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
``` BayerischeMotorenWerke
Your Telegram username
```@bmwtheseries

**Comment by BasharatKar** [comment]
When write device name and codename?

**Comment by ghost** [comment]
@BayerischeMotorenWerke Full information correctly

**Comment by BayerischeMotorenWerke** [comment]
mia1 tissot
https://github.com/BayerischeMotorenWerke/device_xiaomi_tissot/commits/12.1

**Comment by BasharatKar** [comment]
Alright welcome
