### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by putraaxyzo** [ProjectBlaze/maintainership#11]
## Device you want to apply for
```
REDMI NOTE 8/8T GINKGO
```

## Device tree sources

```
https://github.com/putraaxyzo/android_device_xiaomi_ginkgo
https://github.com/putraaxyzo/android_vendor_ginkgo
https://github.com/fiqri19102002/android_kernel_xiaomi_ginkgo
```

## Link to the platform where you have released your unofficial build
```
https://t.me/mweprjkt/44
```

## Other ROM's you maintain officially or unofficially
```
Raven OS [OFFICIAL]
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Weeks/Months/Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@putrazxyo13
```

**Comment by BasharatKar** [comment]
Ok you are accepted welcome to the family
