### ISSUE TITLE
New maintainer for Poco F3 (alioth)

### ISSUE THREAD

**Issue by AbrarNoob** [ProjectBlaze/maintainership#12]
## Device you want to apply for
```
Poco F3 / Mi11x (alioth)
```

## Device tree sources

```
https://github.com/AbrarNoob/device_xiaomi_alioth
https://github.com/AbrarNoob/device_xiaomi_sm8250-common
https://github.com/AbrarNoob/vendor_xiaomi_alioth
https://github.com/EmanuelCN/kernel_xiaomi_sm8250 -b stagging3
```

## Link to the platform where you have released your unofficial build
```
Not released yet
```

## Other ROM's you maintain officially or unofficially
```
None
```

## Bugs on unofficial build
```
Nfc
```

## How long have you been building for?
```
1 year
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
AbrarNoob
```

**Comment by afterallafk** [comment]
Seems everything alright. You tried taking logs for NFC as it is working on Redmi Note 10 Pro & Note 8

**Comment by AbrarNoob** [comment]
Exam was going on so not tried to flash..tester shifted to another rom.
But i will fix it for sure asap.

**Comment by afterallafk** [comment]
> Exam was going on so not tried to flash..tester shifted to another rom. But i will fix it for sure asap.

okay fine

**Comment by thefaizanbashir** [comment]
Oh My Man @AbrarNoob is here.

**Comment by thefaizanbashir** [comment]
What's wrong with your NFC @AbrarNoob ?
You took logs?

**Comment by AbrarNoob** [comment]
> What's wrong with your NFC @AbrarNoob ? You took logs?

Nope..tester flashed he forgot.. recently exam going on so cant flash myself.. but as he has Indian varient and it don't have nfc so me still confused about that.. If it's happening with f3 then will take logs and try to fix .

**Comment by afterallafk** [comment]
> > What's wrong with your NFC @AbrarNoob ? You took logs?
> 
> Nope..tester flashed he forgot.. recently exam going on so cant flash myself.. but as he has Indian varient and it don't have nfc so me still confused about that.. If it's happening with f3 then will take logs and try to fix .

Till then welcome to the team and hope that u will fix NFC soon.

**Comment by thefaizanbashir** [comment]
Are you Buggs Bunny @AbrarNoob ?

**Comment by afterallafk** [comment]
> Are you Buggs Bunny @AbrarNoob ?

yes he is that only he is my friend also

**Comment by AbrarNoob** [comment]
> Are you Buggs Bunny @AbrarNoob ?

Ya..
Me die hard bugs bunny fam😅
