### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by insanejr** [ProjectBlaze/maintainership#14]
## Device you want to apply for
**DEVICE**:MOTO G9 PLUS
**CODENAME**:ODESSA
**MANUFACTURER**:MOTOROLA

## Device tree sources

**TREE DEVICE**
https://github.com/insanejr/android_device_motorola_odessa
**TREE KERNEL**
https://github.com/insanejr/android_kernel_motorola_sm6150
**VENDOR TREE**
https://github.com/insanejr/proprietary_vendor_motorola

## Link to the platform where you have released your unofficial build
```
removed
```

## Other ROM's you maintain officially or unofficially
```
Lineage Os
Spark Os
Pixel Experience plus
Project Arcana
```

## Bugs on unofficial build
```
Dont have
```

## How long have you been building for?
```
02 Weeks
06 Months
01 Year
```

## SELinux status?
```
Enforcing/Permissive
```

## Are you using a prebuilt kernel? If yes, why?
```
No
```

**Contact**
TELEGRAM USERNAME
```
@rafaelodessa

**Comment by BasharatKar** [comment]
I don't see any contribution in trees

**Comment by ghost** [comment]
> I don't see any contribution in trees

True

**Comment by afterallafk** [comment]
> 

How u made official build u kanged our source?
