### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by SKORPION29** [ProjectBlaze/maintainership#15]
## Device you want to apply for
```
Redmi Note 9 Pro (Miatoll)
```

## Device tree sources

```
https://github.com/SKORPION29/android_device_xiaomi_miatoll
https://github.com/SKORPION29/android_device_xiaomi_sm6250-common
https://github.com/SKORPION29/vendor_xiaomi_miatoll
https://github.com/SKORPION29/vendor_xiaomi_sm6250-common
https://github.com/SKORPION29/kernel_xiaomi_sm6250
```

## Link to the platform where you have released your unofficial build
```
Not yet (I was asked to apply with my trees becoz source is wip)
```

## Other ROM's you maintain officially or unofficially
```
Not yet. But released a few builds of other roms unofficially
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2-3 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@SKORPION_29
```

**Comment by BasharatKar** [comment]
You don't have proper authorships not even in a single commit

**Comment by SKORPION29** [comment]
> You don't have proper authorships not even in a single commit

check branch twelve, i just switched to new branch recently

**Comment by BasharatKar** [comment]
I can't see any authorships u gave

**Comment by thefaizanbashir** [comment]
@SKORPION29 lmao, are you using browser to commit? And you're just kanging commits, please learn git first & give proper authorships. You can apply later.

**Comment by afterallafk** [comment]
@thefaizanbashir i talked to him community group u can checkout he said he will fix in an hour

**Comment by afterallafk** [comment]
Ok u r in

**Comment by SKORPION29** [comment]
> Ok u r in

Thanks. Glad to be a part of the team
