### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Musical143143** [ProjectBlaze/maintainership#16]
## Device you want to apply for 
```MI A3
Your device name and codename
laurel_sprout
## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```https://github.com/Musical143143/device_xiaomi_laurel_sprout1.git
https://github.com/Musical143143/Vendor_xiaomi_laurel_sprout.git
https://github.com/Musical143143/kernel_xiaomi_laurel_sprout3.git

```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```
https://t.me/A12_miA3
## Bugs on unofficial build
```
None
```
None
## How long have you been building for?
```
Weeks/Months/Years
```
Months
## SELinux status?
```
Enforcing.
```
Enforcing
## Are you using a prebuilt kernel? If yes, why?
```
No.
```
No
### Telegram username
```
Your Telegram username
```RAYAN
@Universeworldbekind

**Comment by rockstar5495** [comment]
Your device tree seems to be adapted for Cherish where is Blaze. Also you haven't mentioned since how long you are maintaining and which bugs are there if any. If you have released any unofficial Blaze then share link here for the post.

**Comment by Musical143143** [comment]
Yes am maintaining cherish official and no bug and am building rom from 6
moths ago

**Comment by Musical143143** [comment]
Just showed my dt if u accept my request then I will create new blaze -b

**Comment by rockstar5495** [comment]
Release unofficial build for Blaze then share us screenshot of about section and then again apply with blaze trees.

**Comment by rockstar5495** [comment]
Till then we are holding your maintainership.

**Comment by Musical143143** [comment]
Ok, will do that.

**Comment by Musical143143** [comment]
Thank you for your response.

**Comment by BasharatKar** [comment]
Alright you are accepted
