### ISSUE TITLE
New maintainer - r5x

### ISSUE THREAD

**Issue by JaswantTeja** [ProjectBlaze/maintainership#19]
## Device you want to apply for
Realme 5/5i/5s (unified)-r5x
```
Your device name and codename
```
Realme 5i (RMX2030)
## Device tree sources
```
https://github.com/JaswantTeja/device_realme_r5x
https://github.com/JaswantTeja/kernel_realme_r5x
https://github.com/JaswantTeja/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmx_1911/1497
```

## Other ROM's you maintain officially or unofficially
```
Only Blaze
```

## Bugs on unofficial build
```
Offline Charging
```

## How long have you been building for?
```
40 Days
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram
```
@JaswantTeja
```

**Comment by JaswantTeja** [comment]
> @JaswantTeja Ek or Realmeme 🤦‍♂

That Is K Bro. KharaMe

**Comment by BasharatKar** [comment]
@JaswantTeja Trees look fine though

**Comment by rockstar5495** [comment]
@JaswantTeja Fix your device trees i have commented on commit. Then apply again

**Comment by rockstar5495** [comment]
Just fix last 3 commits rest is fine.

**Comment by JaswantTeja** [comment]
> Just fix last 3 commits rest is fine.

Check Again Sir

**Comment by BasharatKar** [comment]
@JaswantTeja Looks fine now

**Comment by JaswantTeja** [comment]
> @JaswantTeja Looks fine now

Ok Sir Can You discuss with your team and tell me what's your response.

**Comment by BasharatKar** [comment]
@JaswantTeja Yeah we will be back soon

**Comment by JaswantTeja** [comment]
> 

Okay thank you sir waiting for your response hoping that I was selected for this.

**Comment by rockstar5495** [comment]
Check your device trees still bringup not proper.

**Comment by ghost** [comment]
can you explain why you have 2 device make files?

**Comment by BasharatKar** [comment]
Better luck next time
