### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by sunil98025** [ProjectBlaze/maintainership#2]
## Device you want to apply for
```
Your device name and codename
X00TD (Asus max pro m1)

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/monu70152/android_kernel_asus_sdm660-1
https://github.com/monu70152/device_asus_X00TD
https://github.com/monu70152/device_asus_sdm660-common_snow
https://github.com/monu70152/vendor_asus_X00TD
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Arcana unofficial but not released yet but all ok in build
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
like 1 month 4 or 5 successful build of arcana me nub still learning try my best s
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
@Monu_ohlyan
```

**Comment by anupam41** [comment]
@monu70152

**Comment by sunil98025** [comment]
Yes sir

**Comment by BasharatKar** [comment]
I am seeing ur tree u don't have proper authorships

**Comment by sunil98025** [comment]
Ok

**Comment by sunil98025** [comment]
As I said I m still learning trying my best

**Comment by BasharatKar** [comment]
I want u to give proper authorships

**Comment by sunil98025** [comment]
Giving from my side

**Comment by sunil98025** [comment]
But sometimes I mess tree that's why reverted

**Comment by BasharatKar** [comment]
Please wait sometime until we discuss

**Comment by sunil98025** [comment]
Ok

**Comment by sunil98025** [comment]
Credit given or commit from my side not stolen

**Comment by thefaizanbashir** [comment]
Man, fix your commit history. Are you making commits using browser?

**Comment by sunil98025** [comment]
Yes

**Comment by sunil98025** [comment]
That's why

**Comment by BasharatKar** [comment]
Please fix your trees and give proper authorships so better luck next time

**Comment by thefaizanbashir** [comment]
You don't know git @monu70152

**Comment by sunil98025** [comment]
I already said me learning

**Comment by sunil98025** [comment]
I didn't hidden that

**Comment by sunil98025** [comment]
Ok

**Comment by afterallafk** [comment]
> That's why

you know git?

**Comment by thefaizanbashir** [comment]
@monu70152 pls learn some git stuff, @BasharatKar made the decision as you can see, YOU'RE REJECTED. You can try again after doing the suggested things :)

**Comment by sunil98025** [comment]
> @monu70152 pls learn some git stuff, @BasharatKar made the decision as you can see, YOU'RE REJECTED. You can try again after doing the suggested things :)

Ok will try next time
