### ISSUE TITLE
New maintainer 

### ISSUE THREAD

**Issue by JaswantTeja** [ProjectBlaze/maintainership#20]
## Device you want to apply for
Realme 5/5i/5s (unified)-r5x
```
Your device name and codename
```
Realme 5i (RMX2030)
## Device tree sources
```
https://github.com/JaswantTeja/device_realme_r5x
https://github.com/JaswantTeja/kernel_realme_r5x
https://github.com/JaswantTeja/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmx_1911/1497
```

## Other ROM's you maintain officially or unofficially
```
Only Blaze
```

## Bugs on unofficial build
```
Offline Charging
```

## How long have you been building for?
```
40 Days
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram
```
@JaswantTeja
```

**Comment by ganesh314159** [comment]
first of all, make one unofficial build, publish it and also take logs while building, if you don't know how to take log, just put >> build.log after make bacon command. next time apply with build logs, now bye.

**Comment by JaswantTeja** [comment]
> first of all, make one unofficial build, publish it and also take logs while building, if you don't know how to take log, just put >> build.log after make bacon command. next time apply with build logs, now bye.

I Have Bulid And The Logs Too
Go Thru This Bro👇
https://api.cirrus-ci.com/v1/task/4877750581329920/logs/build.log

**Comment by JaswantTeja** [comment]
Today I Made One Bulid(GAPPS). As The Team Told Me To Bulid 1.2. So Closing This Now And Keep This Device Hold For Me Bro.
Tq
