### ISSUE TITLE
New maintainer for raphael

### ISSUE THREAD

**Issue by Pc1598** [ProjectBlaze/maintainership#21]
## Device you want to apply for
```
Redmi K20 Pro ( raphael )
```

## Device tree sources

```
https://github.com/Pc1598/blaze_device_xiaomi_raphael
https://github.com/SOVIET-ANDROID/kernel_xiaomi_raphael
https://github.com/Pc1598/vendor_xiaomi_raphael
```

## Link to the platform where you have released your unofficial build
```
https://t.me/redmik20proglobalofficial/1888092
```

## Other ROM's you maintain officially or unofficially
```
ElytraOS Unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@laz_man
```

**Comment by rockstar5495** [comment]
@Pc1598 @afterallafk Basharat ask him whether NFC fixed or not

**Comment by rockstar5495** [comment]
Is NFC fixed or not

**Comment by ghost** [comment]
@Pc1598 In your device tree, why you didn't gave authorship to @rockstar5495 if you didn't fixed on your own?

**Comment by Pc1598** [comment]
I gave authorship to him for first 2 but sepolicy for my device is quite
different from his so i cherry-pick would just say bad object so i had to
change directory and stuff and that would complicate things so i just added
it myself and thanked him in note.

**Comment by ghost** [comment]
@Pc1598 You know you can give authorship through command too right?

**Comment by Pc1598** [comment]
Well i have given it now

**Comment by ghost** [comment]
Ok, your trees looks fine now. @BasharatKar Please have a look.

**Comment by BasharatKar** [comment]
You are accepted

**Comment by Pc1598** [comment]
Yes i do now i will do it right way now then👍
