### ISSUE TITLE
New maintainer (Vince) Redmi 5 Plus

### ISSUE THREAD

**Issue by ritvik-ch** [ProjectBlaze/maintainership#22]
Unofficial Build Download link- https://roms.cirrus-ci.workers.dev/0:/vince/Blaze-v1.1-vince-20220603-1205-VANILLA-UNOFFICIAL.zip

Maintaining Blaze Since- A week

Bugs- Vilte (no fix till now)

Roms Currently maintaining- VoltageOS (official)

Telegram Username -
@ritvik_ch
(Ritvik)

Selinux Status -
Enforcing

CTS-
Passing

Device Sources-
DT-
https://github.com/ritvik-ch/device_xiaomi_vince/tree/Blaze-12.x

Vendor-
https://github.com/ritvik-ch/vendor_xiaomi_vince

Kernel-
https://github.com/GhostMaster69-dev/android_kernel_xiaomi_vince

**Comment by BasharatKar** [comment]
How much time you have been building

**Comment by ritvik-ch** [comment]
5 months almost

**Comment by BasharatKar** [comment]
Ok Fine

**Comment by BasharatKar** [comment]
You are accepted
