### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by blazey66** [ProjectBlaze/maintainership#23]
## Device you want to apply for
Redmi 8/8A/8A Dual
Your device name and codename
Olives

## Device tree sources

```
DT : https://github.com/blazey66/device_xiaomi_olives
Common DT : https://github.com/blazey66/device_xiaomi_sdm439-common
KT : https://github.com/blazey66/kernel_xiaomi_sdm439
VT : https://github.com/blazey66/vendor_xiaomi_olives
Common VT : https://github.com/blazey66/vendor_xiaomi_sdm439-common
```

## Link to the platform where you have released your unofficial build
```
Insert here
https://t.me/projectblaze/24747?single

## Other ROM's you maintain officially or unofficially
```
Insert here
...

## Bugs on unofficial build
```
Wifi QR code scanner 

## How long have you been building for?
```
4 months 

## SELinux status?
```
Enforcing.

## Are you using a prebuilt kernel? If yes, why?
```
No.

### Telegram username
...
Your Telegram username
@blazey66

**Comment by rockstar5495** [comment]
Which ROM you are doing beside this

**Comment by blazey66** [comment]
> Which ROM you are doing beside this

None officaly but Havoc unofficially

**Comment by rockstar5495** [comment]
Do you have knowledge of cherry-pick, git merge and other basic commands

**Comment by rockstar5495** [comment]
Also how to amend a commit

**Comment by blazey66** [comment]
> Do you have knowledge of cherry-pick, git merge and other basic commands

yeah

**Comment by rockstar5495** [comment]
> 

Ok

**Comment by blazey66** [comment]
> Also how to amend a commit

yes sir

**Comment by rockstar5495** [comment]
How will you merge Linux/CAF tag in kernel

**Comment by blazey66** [comment]
> How will you merge Linux/CAF tag in kernel

I don't maintain kernel. but i do know how to upstream kernel version

**Comment by rockstar5495** [comment]
Ok

**Comment by rockstar5495** [comment]
Any timeline for QR code bug till when it will get fixed

**Comment by rockstar5495** [comment]
How many unofficial builds you have made for blaze

**Comment by blazey66** [comment]
> How many unofficial builds you have made for blaze



> Any timeline for QR code bug till when it will get fixed

No idea

**Comment by blazey66** [comment]
> How many unofficial builds you have made for blaze

1

**Comment by rockstar5495** [comment]
Ok fine will let you know
