### ISSUE TITLE
New Maintainer for r5x

### ISSUE THREAD

**Issue by JaswantTeja** [ProjectBlaze/maintainership#24]
## Device you want to apply for
```
Realme 5/5i/5s
RMX1911/RMX2030/RMX1925
```
## Your device name and codename
```
Realme 5i (RMX2030)
```

## Device tree sources
```
https://github.com/JaswantTeja/device_realme_r5x
https://github.com/JaswantTeja/kernel_realme_r5x
https://github.com/JaswantTeja/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Dev/553470
```

## Other ROM's you maintain officially or unofficially
```
Only Blaze
```

## Bugs on unofficial build
```
Offline Charging
```

## How long have you been building for?
```
65 Days
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
JaswantTeja
```

**Comment by ritvik-ch** [comment]
@JaswantTeja You know git basics?

**Comment by afterallafk** [comment]
@JaswantTeja dammn u r building from 65 days u should have applied on 69th day

**Comment by JaswantTeja** [comment]
> @JaswantTeja You know git basics?

Yeah I Know The Git

**Comment by afterallafk** [comment]
@JaswantTeja build error de ccache ka

**Comment by ritvik-ch** [comment]
@JaswantTeja Can I ask a simple question?

**Comment by JaswantTeja** [comment]
> @JaswantTeja dammn u r building from 65 days u should have applied on 69th day

Shit 😂 I Missed The 🙂 Sir

**Comment by JaswantTeja** [comment]
> > @JaswantTeja dammn u r building from 65 days u should have applied on 69th day
> 
> Shit 😂 I Missed That 🙂 Sir
>

**Comment by JaswantTeja** [comment]
> @JaswantTeja Can I ask a simple question?

Ofc 😅

**Comment by ritvik-ch** [comment]
@JaswantTeja What command will you use in git to switch and create new branches of a repository?

**Comment by JaswantTeja** [comment]
> @JaswantTeja What command will you use in git to switch and create new branches of a repository?

git branch to make 
git checkout or git switch to change

**Comment by ritvik-ch** [comment]
@JaswantTeja Do you how to rebase, merge etc?

**Comment by JaswantTeja** [comment]
> @JaswantTeja Do you how to rebase, merge etc?

git rebase -i HEAD~ To Rebase

git merge branchname

**Comment by afterallafk** [comment]
@JaswantTeja tell me how to bringup a dt for rom

**Comment by JaswantTeja** [comment]
> @JaswantTeja tell me how to bringup a dt for rom

LOL The Reason Why I Was Rejected In Before In The v1.1 Update

* Do Changes In AndroidProducts,change the name of rom_r5x,change the name of dependencies

*Add The Maintainer String

*Add The Things Related To Rom

Can See The Bringup Of Blaze

https://github.com/JaswantTeja/device_realme_r5x/commit/67e1cdc99f7563719e6ff18447a066029ae23578

**Comment by ritvik-ch** [comment]
@JaswantTeja Hmm good let me inspect your device trees now

**Comment by SKORPION29** [comment]
@ritvik-ch Will you be able to fix your device side bugs?

**Comment by JaswantTeja** [comment]
> @JaswantTeja Hmm good let me inspect your device trees now

Welcome To My Device 🎄 Sarr

**Comment by JaswantTeja** [comment]
> @ritvik-ch Will you be able to fix your device side bugs?

Ofc Will Try Maximum

**Comment by JaswantTeja** [comment]
> @ritvik-ch Will you be able to fix your device side bugs?

And That's not The Question to @ritvik-ch That's The Question For Me Coz Now I'm Applying

**Comment by SKORPION29** [comment]
@JaswantTeja Yeah asking you only

**Comment by afterallafk** [comment]
> > @ritvik-ch Will you be able to fix your device side bugs?
> 
> And That's not The Question to @ritvik-ch That's The Question For Me Coz Now I'm Applying

whatever better give answers what we asked don't give extra suggestions or try to act oversmart

**Comment by JaswantTeja** [comment]
> @JaswantTeja Yeah asking you only

Lol You Mentioned Him. Anyways I Answered That Sir

**Comment by SKORPION29** [comment]
@JaswantTeja Why do you have dependencies in your dt? Are those needed?

**Comment by afterallafk** [comment]
@JaswantTeja no need r u kid acting like immature u can ignore also

**Comment by afterallafk** [comment]
@afterallafk How to fix ccache error?

**Comment by afterallafk** [comment]
@afterallafk reply in 1 min

**Comment by afterallafk** [comment]
> > @JaswantTeja Yeah asking you only
> 
> Lol You Mentioned Him. Anyways I Answered That Sir

How to fix ccache error?

**Comment by JaswantTeja** [comment]
> @JaswantTeja Why do you have dependencies in your dt? Are those needed?

Yes They are Important Sir.

**Comment by afterallafk** [comment]
> > @JaswantTeja Why do you have dependencies in your dt? Are those needed?
> 
> Yes They are Important Sir.

Tell me that importance i don't have any dependency in my dt.

**Comment by ritvik-ch** [comment]
@JaswantTeja Yes for what?

**Comment by JaswantTeja** [comment]
> > > @JaswantTeja Yeah asking you only
> > 
> > 
> > Lol You Mentioned Him. Anyways I Answered That Sir
> 
> How to fix ccache error?

cd ../.. 
sudo umount /mnt/ccache
sudo rm -rf /mnt/ccache

sudo mkdir /mnt/ccache && sudo mount --bind /home/<instance name or username of ur instance>/.ccache /mnt/ccache

export USECCACHE=1 && export CCACHEEXEC=/usr/bin/ccache && export CCACHE_DIR=/mnt/ccache && ccache -M 100G

**Comment by afterallafk** [comment]
@JaswantTeja I have asked u in 1min it's 2 min

**Comment by JaswantTeja** [comment]
> @JaswantTeja Yes for what?

To Get the Kernel And Blobs In The Vendor Which Are In The Android 11 Sir

**Comment by afterallafk** [comment]
@JaswantTeja why googled?

**Comment by JaswantTeja** [comment]
> @JaswantTeja why googled?

Lol Not Googled One Person Told Me A Long Ago About This When I Got The Error Sir!

**Comment by afterallafk** [comment]
@JaswantTeja My DT is also A11 base still no dependency and still i am able to build with kernel and vendor blobs with your reason my build should have failed? right

**Comment by BasharatKar** [comment]
You are Rejected Go Get Some More Knowledge Better luck next time

**Comment by rockstar5495** [comment]
> @JaswantTeja Why do you have dependencies in your dt? Are those needed?

It shouldn't be an issue whether device has dependencies or not .

**Comment by JaswantTeja** [comment]
> > @JaswantTeja Why do you have dependencies in your dt? Are those needed?
> 
> It shouldn't be an issue whether device has dependencies or not . 

But That Is Not My Original Tree . I Forked From My Device Org And I Know That Dependencies are Needed To Fullfil The Required Things.

**Comment by afterallafk** [comment]
@JaswantTeja to fulfill which requirements

**Comment by JaswantTeja** [comment]
> @JaswantTeja to fulfill which requirements

To Run The Bulid In Jenkins Sir Which Also Be Called As Req To Run The Bulid In Jenkins

**Comment by afterallafk** [comment]
@JaswantTeja u use cirrus or jenkins?

**Comment by JaswantTeja** [comment]
> @JaswantTeja u use cirrus or jenkins?

I Use The Cirrus Ci Sir. I'm also a Team Member of Rom Buliders By Apon Sir

**Comment by JaswantTeja** [comment]
In final words , what you guys are going to tell??
Is i'm accepted or rejected?
Thank You guys.

**Comment by afterallafk** [comment]
> In final words , what you guys are going to tell?? Is i'm accepted or rejected? Thank You guys.

We will inform you soon

**Comment by BasharatKar** [comment]
You are Accepted

**Comment by JaswantTeja** [comment]
> You are Accepted

Tqs For Everything Firstly Sir. Will Not Apply Again for the Maintainership

@rockstar5495 @anupam41 @TechnoStartOfficial @BasharatKar Tq Guys 👍

**Comment by JaswantTeja** [comment]
> @JaswantTeja Improve your knowledge

Okay Thanks For The Suggestion.
