### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Subratam6296** [ProjectBlaze/maintainership#25]
## Device you want to apply for
```
Your device name and codename
```
Redmi Note 7 Pro ( Violet )

## Device tree sources

```
https://github.com/rdx420/S_Device_Xiaomi_violet/tree/Awaken12
https://github.com/SuperiorOS-Devices/kernel_xiaomi_violet/tree/twelve
https://github.com/rdx420/S_vendor_xiaomi_violet/tree/twelve

```

## Link to the platform where you have released your unofficial build
```
https://t.me/RedmiNote7ProChannel/1951

```

## Other ROM's you maintain officially or unofficially
```
AICP , AEX
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Your Telegram username
```@Rdx55

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> ```
> Your device name and codename
> ```
> 
> Redmi Note 7 Pro ( Violet )
> 
> ## Device tree sources
> ```
> https://github.com/rdx420/S_Device_Xiaomi_violet/tree/Awaken12
> https://github.com/SuperiorOS-Devices/kernel_xiaomi_violet/tree/twelve
> https://github.com/rdx420/S_vendor_xiaomi_violet/tree/twelve
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> https://t.me/RedmiNote7ProChannel/1951
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> AICP , AEX
> ```
> 
> ## Bugs on unofficial build
> ```
> None
> ```
> 
> ## How long have you been building for?
> ```
> 2 Years
> ```
> 
> ## SELinux status?
> ```
> Enforcing.
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> ```
> Your Telegram username
> ```@Rdx55
> ```

Your trees look fine and ok from my side and your experience is being shown in your trees

**Comment by BasharatKar** [comment]
Welcome To Team

**Comment by Subratam6296** [comment]
Thanks
