### ISSUE TITLE
New maintainer for Poco x3 pro (vayu)

### ISSUE THREAD

**Issue by Lambada10** [ProjectBlaze/maintainership#26]
## Device you want to apply for
```
Vayu/bhima
```

## Device tree sources

```
https://github.com/lambada-vayu-lab/device_xiaomi_vayu-blaze (master)
https://github.com/Jebaitedneko/android_kernel_xiaomi_vayu (r2)
https://github.com/ArrowOS-Devices/android_vendor_xiaomi_vayu (arrow-12.1)
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/lambadaroms/files/Canary/Blaze-v1.2-vayu-20220620-0451-GAPPS-UNOFFICIAL.zip/download
```

## Other ROM's you maintain officially or unofficially
```
AOSP Extended unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
About a year
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Lambada10
```

**Comment by BasharatKar** [comment]
You are approved
