### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by orkunergun** [ProjectBlaze/maintainership#28]
## Device you want to apply for
```
Redmi 9/Poco M2 (Unified) | lava
```

## Device tree sources

```
https://gitlab.com/R9Lab/DeviceTree
https://gitlab.com/R9Lab/CommonDeviceTree
https://gitlab.com/R9Lab/VendorTree
https://github.com/PixelExperience-Devices/kernel_xiaomi_mt6768
```

## Link to the platform where you have released your unofficial build
```
https://t.me/HelioG85_Updates/511 | Version 1.2
```

## Other ROM's you maintain officially or unofficially
```
Only Cherish Official
```

## Bugs on unofficial build
```
Screenrecorder (normal bug on mt6768 devices)
```

## How long have you been building for?
```
2.5 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/orkunergun
```

**Comment by afterallafk** [comment]
Fine , but move your trees to github it's easy to handle there and also easy to user to checkout as gitlab is little bit complex

**Comment by orkunergun** [comment]
Will I be accepted when I do this?

**Comment by orkunergun** [comment]
> Fine , but move your trees to github it's easy to handle there and also easy to user to checkout as gitlab is little bit complex

Moved to GitHub rn https://GitHub.com/MT6768

**Comment by rockstar5495** [comment]
@orkunergun use proper naming convention for your device tree, common tree, vendor tree also if possible put in your own repo instead of org

**Comment by orkunergun** [comment]
> 

Organization is good for me But I will do this too

**Comment by orkunergun** [comment]
> @orkunergun use proper naming convention for your device tree, common tree, vendor tree also if possible put in your own repo instead of org

I renamed this repos now
Also I want to use organization because it looks more organized

**Comment by afterallafk** [comment]
@orkunergun From my side it is Accepted

**Comment by orkunergun** [comment]
> @orkunergun From my side it is Accepted

Okey thanks 👍 Waiting for other devs

**Comment by BasharatKar** [comment]
Accepted
