### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by ItsAdityan** [ProjectBlaze/maintainership#3]
## Device you want to apply for
```
Redmi 5 plus aka vince
```

## Device tree sources

```
https://github.com/ItsAdityan/android_device_xiaomi_vince
https://github.com/ItsAdityan/android_kernel_xiaomi_vince
https://github.com/ItsAdityan/android_vendor_xiaomi_vince
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
CipherOS
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 year
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Aknx31
```

**Comment by thefaizanbashir** [comment]
@ItsAdityan where is link to unofficial build?

**Comment by afterallafk** [comment]
As far to concern you trees look fine to me @ItsAdityan

**Comment by ghost** [comment]
Yes trees seems fine

**Comment by thefaizanbashir** [comment]
I never said trees aren't good @afterallafk but where is link to unofficial build?

**Comment by thefaizanbashir** [comment]
Trees are fine :)

**Comment by thefaizanbashir** [comment]
Okay I'll tell my opinion, you can't apply for official without building unofficial first. Your trees look fine, but build unofficial first. Then attach link. For now it'll stay under review

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> ```
> Redmi 5 plus aka vince
> ```
> 
> ## Device tree sources
> ```
> https://github.com/ItsAdityan/android_device_xiaomi_vince
> https://github.com/ItsAdityan/android_kernel_xiaomi_vince
> https://github.com/ItsAdityan/android_vendor_xiaomi_vince
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> Insert here
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> CipherOS
> ```
> 
> ## Bugs on unofficial build
> ```
> None
> ```
> 
> ## How long have you been building for?
> ```
> 1 year
> ```
> 
> ## SELinux status?
> ```
> Enforcing.
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> ```
> @Aknx31
> ```

Accepted
