### ISSUE TITLE
New maintainer for Redmi Note 11 

### ISSUE THREAD

**Issue by sayann70** [ProjectBlaze/maintainership#30]
## Device you want to apply for
```
Redmi Note 11 - spes
```

## Device tree sources

```
https://github.com/sayann70/device_xiaomi_spes
https://github.com/sayann70/kernel_xiaomi_spes_header
https://github.com/sayann70/vendor_xiaomi_spes
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RedmiNote11_Updates/64
```

## Other ROM's you maintain officially or unofficially
```
ricedroid unofficially
```

## Bugs on unofficial build
```
wifi calling 
```

## How long have you been building for?
```
6 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
yes , because spes has no kernel sources 
```

### Telegram username
```
https://t.me/sayann70
```

**Comment by BasharatKar** [comment]
Trees looks fine with proper authorships

**Comment by afterallafk** [comment]
Your trees are fine. Now answer some questions 
How to give authorships regardless of cherry-pick?

**Comment by sayann70** [comment]
> Your trees are fine. Now answer some questions How to give authorships regardless of cherry-pick?

as far as i know, when we cherry-pick authorship gets generated automatically, from the commit it was picked from.

**Comment by afterallafk** [comment]
> > Your trees are fine. Now answer some questions How to give authorships regardless of cherry-pick?
> 
> as far as i know, when we cherry-pick authorship gets generated automatically, from the commit it was picked from.

ok no problem not a big issue you will learn as far you get experience. Can you tell me how to find the author details of a commit means it's github username and email ?

**Comment by sayann70** [comment]
> > > Your trees are fine. Now answer some questions How to give authorships regardless of cherry-pick?
> > 
> > 
> > as far as i know, when we cherry-pick authorship gets generated automatically, from the commit it was picked from.
> 
> ok no problem not a big issue you will learn as far you get experience. Can you tell me how to find the author details of a commit means it's github username and email ?

if we use "git show < commit id >" then it will show authors username and email

**Comment by afterallafk** [comment]
> > > > Your trees are fine. Now answer some questions How to give authorships regardless of cherry-pick?
> > > 
> > > 
> > > as far as i know, when we cherry-pick authorship gets generated automatically, from the commit it was picked from.
> > 
> > 
> > ok no problem not a big issue you will learn as far you get experience. Can you tell me how to find the author details of a commit means it's github username and email ?
> 
> if we use "git show < commit id >" then it will show authors username and email

great another easy method is also there i will tell u later if you were accepted in team

**Comment by BasharatKar** [comment]
You are good so far

**Comment by BasharatKar** [comment]
You are accepted
