### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by JaswantTeja** [ProjectBlaze/maintainership#31]
## Device you want to apply for
```
Realme 5/5i/5s
RMX1911/RMX2030/RMX1925
```

## Your device name and codename
```
Realme 5i - RMX2030 (Bear By Realme)
```

## Device tree sources

```
https://github.com/JaswantTeja/device_realme_r5x
https://github.com/JaswantTeja/kernel_realme_r5x
https://github.com/JaswantTeja/vendor_realme_r5x
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Dev/570463
```

## Other ROM's you maintain officially or unofficially
```
Only Blaze From v1.1
```

## Bugs on unofficial build
```
Offline Charging (It Works But We Can't Get The Animation)
```

## How long have you been building for?
```
More Than 3 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
JaswantTeja
```

**Comment by mrtechnostart** [comment]
https://github.com/JaswantTeja/device_realme_r5x/commit/0d4447436a018629c21a4aacc4c31098897adf6f#diff-247ee86229a709a6e2eedfc1d3c4a557825aee073e20b0112ab76f4ca8e4bc4eR353

What say About this one bro?

**Comment by mrtechnostart** [comment]
You didn't even resolved conflicts properly, do git reset and pick last of your both commit again

**Comment by JaswantTeja** [comment]
> You didn't even resolved conflicts properly, do git reset and pick last of your both commit again

I Didn't Saw That Sorry,I will resolve Confilcts

**Comment by JaswantTeja** [comment]
> https://github.com/JaswantTeja/device_realme_r5x/commit/0d4447436a018629c21a4aacc4c31098897adf6f#diff-247ee86229a709a6e2eedfc1d3c4a557825aee073e20b0112ab76f4ca8e4bc4eR353
> 
> What say About this one bro?

And Also That's 12.1 Branch,so Please Go Through Blaze

**Comment by mrtechnostart** [comment]
Firstly make blaze as your default branch, rest for me everything seems good, now basharat will take final calls

**Comment by mrtechnostart** [comment]
After discussing with team, you are considered accepted
