### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by beingashwani** [ProjectBlaze/maintainership#32]
## Device you want to apply for
``` Realme 5 pro
Your device name and codename
``` RMX1971

## Device tree sources
<!-- https://github.com/Techy0302/device_realme_RMX1971
https://github.com/Techy0302/device_realme_sdm710-common
https://github.com/Techy0302/vendor_realme_sdm710-common
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
``` Officially
Insert here
``` EternityOS 

## Bugs on unofficial build
``` 
None
```

## How long have you been building for?
``` 1 
Weeks/Months/Years
``` years

## SELinux status?
``` Enforcing
Enforcing.
``` 

## Are you using a prebuilt kernel? If yes, why?
``` No
No.
```

### Telegram username
``` ashwani_02
Your Telegram username
```

**Comment by BasharatKar** [comment]
@Techy0302 U haven't done any contribution in trees

**Comment by beingashwani** [comment]
> @Techy0302 U haven't done any contribution in trees

Bro i have this devices very new thats why no contributions..

**Comment by afterallafk** [comment]
which device is this?

**Comment by beingashwani** [comment]
Realme 5 pro.. RMX1971

**Comment by afterallafk** [comment]
> Realme 5 pro.. RMX1971

old maintainer was having bootloop issues after rebooting did u tried this u have this issue or not.

**Comment by beingashwani** [comment]
Nope bro i didnt faced...might be he was using kernel version which are older as this issue was occured in a kernel version which was not recommended to build with.

**Comment by afterallafk** [comment]
> Nope bro i didnt faced...might be he was using kernel version which are older as this issue was occured in a kernel version which was not recommended to build with.

ok nice when u build latest?

**Comment by beingashwani** [comment]
U m i did before 1 or 2 weeks thats also eng build...i will do a build today itself with latest source..

**Comment by afterallafk** [comment]
> U m i did before 1 or 2 weeks thats also eng build...i will do a build today itself with latest source..

ok after you complete build then check the issue once for our confirmation. Then we will proceed further.

**Comment by beingashwani** [comment]
Ok bro sure

**Comment by c0pt4n** [comment]
> Ok bro sure

Did u do the build?
