### ISSUE TITLE
New maintainer chime

### ISSUE THREAD

**Issue by qwertyuiii-code** [ProjectBlaze/maintainership#33]
## Device you want to apply for
PocoM3/Redmi9T
## Device tree sources

https://gitlab.com/chimeOSS/device_xiaomi_chime
https://github.com/qwertyuiii-code/kernel_xiaomi_chime-1
https://github.com/chimeOSS/vendor_xiaomi_chime
```

## Link to the platform where you have released your unofficial build
Mega.nz

## Other ROM's you maintain officially or unofficially
CherishOS (Official)

## Bugs on unofficial build
None

## How long have you been building for?
1 year

## SELinux status?
Enforcing.

## Are you using a prebuilt kernel? If yes, why?
No

## Contact
### Telegram 
@chikoni_uwu

**Comment by BasharatKar** [comment]
Push your trees to github rather than gitlab

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> PocoM3/Redmi9T
> 
> ## Device tree sources
> https://gitlab.com/chimeOSS/device_xiaomi_chime https://github.com/qwertyuiii-code/kernel_xiaomi_chime-1 https://github.com/chimeOSS/vendor_xiaomi_chime
> 
> ```
> 
> ## Link to the platform where you have released your unofficial build
> Mega.nz
> 
> ## Other ROM's you maintain officially or unofficially
> CherishOS (Official)
> 
> ## Bugs on unofficial build
> None
> 
> ## How long have you been building for?
> 1 year
> 
> ## SELinux status?
> Enforcing.
> 
> ## Are you using a prebuilt kernel? If yes, why?
> No
> 
> ## Contact
> ### Telegram 
> @chikoni_uwu
> ```

And no contributions of yours i can only see conquer os lead's contributions where are your commits?

**Comment by qwertyuiii-code** [comment]
Its dt based on tool for lineage os and for the most part, we invest in the vendor, updating it, thereby eliminating bugs that "climb out" when used, which the testers did not tell us about or did not find.

**Comment by qwertyuiii-code** [comment]
> Push your trees to github rather than gitlab

Vendor source we cant push on github (big size)

**Comment by BasharatKar** [comment]
You are accepted
