### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by akmacc** [ProjectBlaze/maintainership#36]
## Device you want to apply for
```
Realme x3 / RMX2081
```

## Device tree sources

```
https://github.com/akmacc/blaze_device_realme_x3
https://github.com/akmacc/android_kernel_realme_x3
https://github.com/akmacc/android_vendor_realme_x3
```

## Link to the platform where you have released your unofficial build
```
https://t.me/RealmeX3Updates
```

## Other ROM's you maintain officially or unofficially
```
Unofficially maintain derpfest
```

## Bugs on unofficial build
```
DT2W bug I'm working on it
```

## How long have you been building for?
```
Years, i have own server 
```

## SELinux status?
```
Permissive 

```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact

```
@A_k_0_5
```

**Comment by afterallafk** [comment]
https://github.com/akmacc/blaze_device_realme_x3/commit/724aaaecba3d04515ec35dd9c6af1aacfdfc7e17 what do you mean by adopt ? It's bringup and there's a typo error at one point correct it

**Comment by afterallafk** [comment]
https://github.com/akmacc/blaze_device_realme_x3/commit/93774c36a8ae214057d73d7a8cf96e4cf454959d
https://github.com/akmacc/blaze_device_realme_x3/commit/4d13bc2bb498e8187be177fd783f7d3e8cc26c37
https://github.com/akmacc/blaze_device_realme_x3/commit/22ad5e02f306d45921c1367de6592bc15dc7c239

You can squash these three commits in one as it is related to gcam go only. So, it's better squash them rather then committing individually.

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> ```
> Realme x3 / RMX2081
> ```
> 
> ## Device tree sources
> ```
> https://github.com/akmacc/blaze_device_realme_x3
> https://github.com/akmacc/android_kernel_realme_x3
> https://github.com/akmacc/android_vendor_realme_x3
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> https://t.me/RealmeX3Updates
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> Unofficially maintain derpfest
> ```
> 
> ## Bugs on unofficial build
> ```
> DT2W bug I'm working on it
> ```
> 
> ## How long have you been building for?
> ```
> Years, i have own server 
> ```
> 
> ## SELinux status?
> ```
> Permissive 
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ```
> @A_k_0_5
> ```

you have mentioned you have been unofficially maintaining derpfest. So, have you build blaze before applying and fulfilled condition of maintaining blaze 1 months and where is the unofficial build release platform?

**Comment by akmacc** [comment]
Hi could you please check again

**Comment by afterallafk** [comment]
> Hi could you please check again

ohh Okay we found your unofficial build post.

**Comment by afterallafk** [comment]
Ok you are accepted. Welcome to the team ! Enjoy your Journey with us.

**Comment by akmacc** [comment]
Thanks

**Comment by qwertyuiii-code** [comment]
welcome bro
