### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Sachin9822** [ProjectBlaze/maintainership#37]
## Device you want to apply for
```
Mi A1 tissot
```

## Device tree sources

```
https://github.com/Sachin9822/android_device_xiaomi_tissot/tree/ProjectBlaze
https://github.com/Sachin9822/device_xiaomi_msm8953-common/tree/ProjectBlaze
https://github.com/Sachin9822/cakeby_kernel/tree/NON-OC
https://github.com/Sachin9822/vendor_xiaomi_tissot/tree/ProjectBlaze
https://github.com/Sachin9822/vendor_xiaomi_msm8953-common/tree/ProjectBlaze
```

## Link to the platform where you have released your unofficial build
```
https://sourceforge.net/projects/sachin-custom-roms/files/Project-Blaze/
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
1 month
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Sachin9822
```

**Comment by c0pt4n** [comment]
@Sachin9822 nice

**Comment by afterallafk** [comment]
@Sachin9822 by looking your trees it looks like you don't have git knowledge. Please learn the following git commit, cherrypick , authorship etc.

**Comment by c0pt4n** [comment]
@afterallafk nice

**Comment by Sachin9822** [comment]
@afterallafk 
now i learn cherrypick and authorship 
check git Device tree

**Comment by afterallafk** [comment]
> https://github.com/Sachin9822/android_device_xiaomi_tissot/tree/ProjectBlaze

https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/a00fe796aaa46b0c029967342e55a71569c21f10
https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/4833f695ab02802313e10bb1ec992a0d602f66e7
https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/2190bf0303d3c91d79757a234eeda48d36b6a86e
https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/f9e64fcd52987839ffe3dcf4db54afbbe87648ed
https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/1372ead74c5494112e19ce192aa08d16d179d3f8

Overall, do bringup properly and cleanup your trees as it is having derps and remove pixel launcher related commits.

**Comment by c0pt4n** [comment]
how to do cherry-pick?

**Comment by afterallafk** [comment]
> @afterallafk now i learn cherrypick and authorship check git Device tree

https://github.com/Sachin9822/device_xiaomi_msm8953-common/commits/ProjectBlaze 
cleanup this too i mean your common tree

**Comment by Sachin9822** [comment]
> > https://github.com/Sachin9822/android_device_xiaomi_tissot/tree/ProjectBlaze
> 
> [Sachin9822/android_device_xiaomi_tissot@a00fe79](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/a00fe796aaa46b0c029967342e55a71569c21f10) [Sachin9822/android_device_xiaomi_tissot@4833f69](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/4833f695ab02802313e10bb1ec992a0d602f66e7) [Sachin9822/android_device_xiaomi_tissot@2190bf0](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/2190bf0303d3c91d79757a234eeda48d36b6a86e) [Sachin9822/android_device_xiaomi_tissot@f9e64fc](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/f9e64fcd52987839ffe3dcf4db54afbbe87648ed) [Sachin9822/android_device_xiaomi_tissot@1372ead](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/1372ead74c5494112e19ce192aa08d16d179d3f8)
> 
> Overall, do bringup properly and cleanup your trees as it is having derps and remove pixel launcher related commits.

i now check i have already removed the pixel launcher 
and have built V2.1 version and using it

**Comment by orkunergun** [comment]
> > > https://github.com/Sachin9822/android_device_xiaomi_tissot/tree/ProjectBlaze
> > 
> > 
> > [Sachin9822/android_device_xiaomi_tissot@a00fe79](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/a00fe796aaa46b0c029967342e55a71569c21f10) [Sachin9822/android_device_xiaomi_tissot@4833f69](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/4833f695ab02802313e10bb1ec992a0d602f66e7) [Sachin9822/android_device_xiaomi_tissot@2190bf0](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/2190bf0303d3c91d79757a234eeda48d36b6a86e) [Sachin9822/android_device_xiaomi_tissot@f9e64fc](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/f9e64fcd52987839ffe3dcf4db54afbbe87648ed) [Sachin9822/android_device_xiaomi_tissot@1372ead](https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/1372ead74c5494112e19ce192aa08d16d179d3f8)
> > Overall, do bringup properly and cleanup your trees as it is having derps and remove pixel launcher related commits.
> 
> i now check i have already removed the pixel launcher

U need to remove commits

**Comment by afterallafk** [comment]
> >

cleanup means not to commit cleanup it means you need to clean your dt and remove useless commits which were marked to you.

**Comment by orkunergun68** [comment]
@afterallafk 👍👍👍👍

**Comment by Sachin9822** [comment]
> 
Done

**Comment by Sachin9822** [comment]
Done

**Comment by afterallafk** [comment]
> https://github.com/Sachin9822/android_device_xiaomi_tissot/tree/ProjectBlaze

https://github.com/Sachin9822/android_device_xiaomi_tissot/commit/ef12570b1e868ee95101b30414e0661bb61fd6e3#diff-681043dd2ca646ba77443003ccc1003e07fbbae38a896e780f041ea167c7a2e6R23 here B should be small and bringup does not requires author. Do those commits which were earlier.

**Comment by Sachin9822** [comment]
ok made the changes

**Comment by Sachin9822** [comment]
> how to do cherry-pick?

first - 
`git remote add any_name REPO_LINK`
 `git fetch any_name`
`git cherry-pick COMMIT_HASH`

**Comment by afterallafk** [comment]
> > how to do cherry-pick?
> 
> first - `git remote add any_name REPO_LINK` `git fetch any_name` `git cherry-pick COMMIT_HASH`

ok tell me i am giving you a situation. Suppose your device got wifi issues that wifi is not working. How would you fix it? Will you change the tree or will you try fixing it in the current tree? Also what procedure will you follow to fix this issue?

**Comment by c0pt4n** [comment]
I will put this applicant on hold until we release v2.2 after that u can comment here with your published build link
BUT KEEP IN MIND THAT YOUR DT SHOULD BE IMPROVED SO THAT WE CAN MAKE SURE YOU KNOW ENOUGH GIT...
GOOD LUCK

**Comment by Sachin9822** [comment]
> > > how to do cherry-pick?
> > 
> > 
> > first - `git remote add any_name REPO_LINK` `git fetch any_name` `git cherry-pick COMMIT_HASH`
> 
> ok tell me i am giving you a situation. Suppose your device got wifi issues that wifi is not working. How would you fix it? Will you change the tree or will you try fixing it in the current tree? Also what procedure will you follow to fix this issue?

fixing it in current tree 
Procedure:
take logs find the error and will try to search it on google and try to find commit to fix it

**Comment by Sachin9822** [comment]
> I will put this applicant on hold until we release v2.2 after that u can comment here with your published build link BUT KEEP IN MIND THAT YOUR DT SHOULD BE IMPROVED SO THAT WE CAN MAKE SURE YOU KNOW ENOUGH GIT... GOOD LUCK

ok sure

**Comment by afterallafk** [comment]
> google

why to search on google when github is available for developers?

**Comment by Sachin9822** [comment]
> > google
> 
> why to search on google when github is available for developers?

yea you are right searching on GitHub would give me better results
