### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by chuspita** [ProjectBlaze/maintainership#38]
## Device you want to apply for
```
Sweet
```

## Device tree sources

```https://github.com/chuspita/device_xiaomi_sweet
https://github.com/OmnitrixKernel/kernel_xiaomi_sweet
https://github.com/chuspita/vendor_xiaomi
https://github.com/chuspita/device_xiaomi_sm6150
```

## Link to the platform where you have released your unofficial build
```
[[Insert here](https://sourceforge.net/projects/sweet-roms/)]
```

## Other ROM's you maintain officially or unofficially
```
SparkOS, Xtended, Bananadroid, CherishOS, Havo, Legion, Ricedroid....
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
A couple of years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
[Your Telegram username](https://t.me/franlop77)
```

**Comment by OmarAlCoptan** [comment]
@chuspita Nice

**Comment by BasharatKar** [comment]
Which official rom u maintain?

**Comment by chuspita** [comment]
I have not been able to maintain any ROM officially, because there are almost no roms that do not have an official maintainer

**Comment by chuspita** [comment]
I haven't compiled blaze yet, but I have no problem doing it, if you need it

**Comment by BasharatKar** [comment]
You have only given the common tree link

**Comment by c0pt4n** [comment]
> I haven't compiled blaze yet, but I have no problem doing it, if you need it

Then how no bugs and you didn't compile it?

**Comment by OmarAlCoptan** [comment]
@OmarAlCoptan @Ba_Sh_ArAT

**Comment by chuspita** [comment]
because I have used my latest trees, in different roms and they are really very stable...I'm not saying it, the people who download my roms tell me

**Comment by BasharatKar** [comment]
Show me the trees not the common one

**Comment by chuspita** [comment]
https://github.com/chuspita/device_xiaomi_sweet

**Comment by c0pt4n** [comment]
> because I have used my latest trees, in different roms and they are really very stable...I'm not saying it, the people who download my roms tell me

Okay send the trees used in compiling and build unofficial Blaze

**Comment by chuspita** [comment]
ok...I'll start building blaze...thanks

**Comment by NRanjan-17** [comment]
> I haven't compiled blaze yet, but I have no problem doing it, if you need it

Before applying here you should read this: https://github.com/ProjectBlaze/maintainership/blob/12.1/maintainerreq.md

**Comment by BasharatKar** [comment]
@chuspita haven't u build the unofficial of blaze first then why you applied?

**Comment by chuspita** [comment]
Because I have heard very good things about this ROM, and honestly I would like to keep this ROM, I like ROMS that are stable and reliable and with a future... and I really believe that this is one of them

**Comment by BasharatKar** [comment]
Our source is not ready yet so will notify you when it is ready to build and reapply later.

**Comment by chuspita** [comment]
Ok Sir, I'll wait then for them to let me know...thank you very much again

**Comment by chuspita** [comment]
In case you are interested, I am in a group of compilers for Sweet, you can see that there are important people in the world of custom roms

**Comment by BasharatKar** [comment]
I would rather like you to stick to the topic not the other things and the issue is closed currently see u back later after reapplying
