### ISSUE TITLE
New Maintainer 

### ISSUE THREAD

**Issue by janakniraula** [ProjectBlaze/maintainership#39]
## Device you want to apply for
```
Mi439 (redmi 8,8a,8a dual, 7a)
```

## Device tree sources

```
Device Tree:
https://github.com/Mi-Thorium/android_device_xiaomi_Mi439

Common tree:
https://github.com/Mi-Thorium/android_device_xiaomi_mithorium-common

Kernel:
https://github.com/mi-sdm439/android_kernel_xiaomi_sdm439

Vendor: 
https://github.com/Mi-Thorium/proprietary_vendor_xiaomi_Mi439

Common Vendor : https://github.com/Mi-Thorium/proprietary_vendor_xiaomi_mithorium-common
```

## Link to the platform where you have released your unofficial build
```
t.me/jbuilds77
```

## Other ROM's you maintain officially or unofficially
```
I am also maintainer of eternity os for latest they are releasing. Unofficially I have built cherishos, evolution X, spark Os, CrDroid
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Since 2 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@janakniraula_2017
```

**Comment by rockstar5495** [comment]
you haven't done bringup for blaze also make 1 unofficial build

**Comment by janakniraula** [comment]
Thank you for your response I am on it. I am making unofficial build of
blaze.
