### ISSUE TITLE
Poco X3 pro maintainership request

### ISSUE THREAD

**Issue by clhexftw** [ProjectBlaze/maintainership#4]
## Device you want to apply for : Poco X3 Pro
```
Your device name and codename : vayu / bhima
```

## Device tree sources

* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable

https://github.com/clhexvayulab/android_device_xiaomi_vayu-blaze
https://github.com/clhexvayulab/kernel_xiaomi_vayu
https://github.com/clhexvayulab/android_vendor_xiaomi_vayu

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Project Lighthouse , Cipher others dropped
```

## Bugs on unofficial build
```

```

## How long have you been building for?
```
Weeks/Months/Years: 
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Your Telegram username: @clhexftw
```

**Comment by afterallafk** [comment]
https://github.com/clhexvayulab/android_device_xiaomi_vayu-blaze/commit/a3f1645543595de8aa1c47141fd9cb882785c225
Don't you think it's over volume?

**Comment by rockstar5495** [comment]
Have you already built unofficial if yes then what are bugs in it also how long you are making ROMs

**Comment by clhexftw** [comment]
@afterallafk well i cant ppl made habits in stock rom so i just gave a fix also they r free to use less than 100%

**Comment by clhexftw** [comment]
@rockstar5495 well i talked abt it i preapplied to save my time bro (note: i will release publicly only wen build boots and basic stuffs are completely working ) leave this headace on me vmro

**Comment by BasharatKar** [comment]
@rockstar5495 he is making test build until then application will be on hold

**Comment by rockstar5495** [comment]
> @rockstar5495 well i talked abt it i preapplied to save my time bro (note: i will release publicly only wen build boots and basic stuffs are completely working ) leave this headace on me vmro

just send us about phone when booted

**Comment by afterallafk** [comment]
> @afterallafk well i cant ppl made habits in stock rom so i just gave a fix also they r free to use less than 100%

okay but 100 is much over volume better use 90 or 95

**Comment by thefaizanbashir** [comment]
@clhexftw unofficial build is necessary before applying na? Where is unofficial build?

**Comment by thefaizanbashir** [comment]
I can't understand what you did here? 
https://github.com/clhexvayulab/android_device_xiaomi_vayu-blaze/commit/bd7308bd517a0081429916d52fa70d14fd1d68f9 
@clhexftw

**Comment by rockstar5495** [comment]
> I can't understand what you did here? [clhexvayulab/android_device_xiaomi_vayu-blaze@bd7308b](https://github.com/clhexvayulab/android_device_xiaomi_vayu-blaze/commit/bd7308bd517a0081429916d52fa70d14fd1d68f9) @clhexftw

He just removed GCam Go as Arrow track GCam from their repo so its fine

**Comment by afterallafk** [comment]
> I can't understand what you did here? [clhexvayulab/android_device_xiaomi_vayu-blaze@bd7308b](https://github.com/clhexvayulab/android_device_xiaomi_vayu-blaze/commit/bd7308bd517a0081429916d52fa70d14fd1d68f9) @clhexftw

He nuked GcamGo leave it rest is fine

**Comment by thefaizanbashir** [comment]
GG

**Comment by clhexftw** [comment]
@rockstar5495 fine XD

**Comment by clhexftw** [comment]
@thefaizanbashir are i asked abt it on tg already adtiya said okay (it was to save my time ) and as i said testing unofifical and sharing everything is my personal guarantee

**Comment by clhexftw** [comment]
@afterallafk i nuked gcamgo bcz i will add gcam/opencam in future builds

**Comment by clhexftw** [comment]
also if u want i will clone gcamgo package and will add it back

**Comment by thefaizanbashir** [comment]
I understand your concern @clhexftw but when unofficial build will be ready?

**Comment by clhexftw** [comment]
@thefaizanbashir till tommrow (for sure) i got nfc error otherwise it was today only btw  i shared error logs in grp too aditya checked and fixed it

**Comment by thefaizanbashir** [comment]
Take your time

**Comment by BasharatKar** [comment]
Ok Welcome To Our Team
