### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by janakniraula** [ProjectBlaze/maintainership#40]
## Device you want to apply for
```
Mi439(Redmi 8, 8A,8A dual, 7A)
```

## Device tree sources

```
Device Tree:
https://github.com/janakniraula/android_device_xiaomi_Mi439

Common tree:
https://github.com/janakniraula/android_device_xiaomi_mithorium-common

Kernel:
https://github.com/janakniraula/android_kernel_xiaomi_sdm439

Vendor: 
https://github.com/janakniraula/proprietary_vendor_xiaomi_Mi439

Common Vendor : 
https://github.com/janakniraula/proprietary_vendor_xiaomi_mithorium-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/jbuilds77/35
```

## Other ROM's you maintain officially or unofficially
```
Eternity(Official),ProjectBlaze Evolution X, Cherish, Spark, VoidUI
```

## Bugs on unofficial build
```
In blaze when screen record completes the screen recording is green it is only green.
```

## How long have you been building for?
```
since 2 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@janakniraula_2017
```

**Comment by rockstar5495** [comment]
do proper bringup first.

**Comment by afterallafk** [comment]
I can see you are building so many roms and only one official ROM, rathar than building etc etc roms pick one or two and stick to them for maintaining. 
Also as mentioned above earlier your bringup is not proper and that signifies that you don't know git.
Please learn git.

**Comment by janakniraula** [comment]
okay thank you
