### ISSUE TITLE
New maintainer (bitra)

### ISSUE THREAD

**Issue by cristianvaz** [ProjectBlaze/maintainership#43]
## Device you want to apply for
...
Your device name and codename
Realme GT Neo 2 (bitra)

## Device tree sources

```
https://github.com/cristianvaz/device_realme_bitra
https://github.com/cristianvaz/device_realme_sm8250-common
https://github.com/PixelOS-Devices/vendor_realme_bitra
https://github.com/PixelOS-Devices/vendor_realme_sm8250-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/cristianvazsupport/34338
```

## Other ROM's you maintain officially or unofficially
```
Pixelos official
```

## Bugs on unofficial build
```
None, missing aux con camera only
```

## How long have you been building for?
```
2 years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
cristianvaz
```

**Comment by afterallafk** [comment]
Already accepted got good feedback about your profile.
