### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by beingashwani** [ProjectBlaze/maintainership#44]
## Device you want to apply for
``` Realme 3 pro
Your device name and codename
``` RMX1851

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
--> 
``` https://github.com/ashwani212/Device_Realme_RMX1851/commits/blaze

https://github.com/user/device_brand_codename
https://github.com/user/kernel_brand_codename
https://github.com/user/vendor_brand_codename
```

## Link to the platform where you have released your unofficial build
``` 
Insert here
```
https://t.me/RMX3ProUpdates/277

## Other ROM's you maintain officially or unofficially
``` Official DroidXUI, SuperiorOS unofficial
Insert here
```

## Bugs on unofficial build
``` 
None
```

## How long have you been building for?
``` more than 1 year
Weeks/Months/Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
Your Telegram username
``` @Noobie_ashwani

**Comment by beingashwani** [comment]
I guess i didnt filled my year experience in way, so i would like to tell i m building from 1 year, maintaining droidxui official, SuperiOS Unofficial for now.
So i m mentioning this here, i hope its fine.

**Comment by BasharatKar** [comment]
Welcome to the team.
