### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AnilShebin** [ProjectBlaze/maintainership#45]
## Device you want to apply for
```
Realme 5 Pro (RMX1971)
```

## Device tree sources

```
https://github.com/AnilShebin/device_realme_RMX1971
   
https://github.com/AnilShebin/device_realme_sdm710-common
  
https://github.com/AnilShebin/kernel_realme_RMX1971
  
https://gitlab.com/AnilShebin/vendor_realme_rmx1971.git

https://github.com/AnilShebin/vendor_realme_sdm710-common
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Realme5Pro_Downloads/1821 
```

## Other ROM's you maintain officially or unofficially
```
CrDroid,Pixel Experience (Unofficial)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
5 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@AnilShebin
```

**Comment by afterallafk** [comment]
https://github.com/AnilShebin/device_realme_RMX1971/commit/1bce4f40ecbc54ed219c8e9937c3e6984adc02d1

Update this flag to get blur support from source.
We use TARGET_SUPPORTS_BLUR := true

**Comment by afterallafk** [comment]
Rest all ok your trees look clean to me
+1 from my side

**Comment by AnilShebin** [comment]
Sir ,Blur support flag Updated as per Source.

**Comment by afterallafk** [comment]
> Sir ,Blur support flag Updated as per Source.

https://github.com/ProjectBlaze/vendor_blaze/commit/386d67cbf3f6541be643c628b1bc53a3a4188610#

check here this is needed

**Comment by rockstar5495** [comment]
revert both commits as it doesn't make sense in one commit you removed and in very next you added back same
https://github.com/AnilShebin/device_realme_RMX1971/commit/ab052817cd9f174aaf971a909913c02d4fbf0175
https://github.com/AnilShebin/device_realme_RMX1971/commit/ef254e5c760a2f91703c4715c133435bfa1bac38
and rebase trees
also instead of sourceforge provide channel link where you released your ROM's

**Comment by AnilShebin** [comment]
Sir , Rebase done and telegram link has been given instead of  sourceforge.

**Comment by rockstar5495** [comment]
Everything fine now. You are accepted.
