### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by Vansh-Prjkts** [ProjectBlaze/maintainership#46]
## Device you want to apply for
```
Realme 3 Pro (RMX1851)
```

## Device tree sources

```
https://github.com/Vansh-Prjkts/device_realme_RMX1851
https://github.com/Vansh-Prjkts/kernel_realme_sdm710
https://github.com/Vansh-Prjkts/android_vendor_RMX1851
```

## Link to the platform where you have released your unofficial build
```
My Telegram Channel :- https://t.me/vanshprojects 
```

## Other ROM's you maintain officially or unofficially
```
Yes I Maintained Some Roms Unofficially Ricedroid , Pixel Experience , EvoX , Bliss , Boitleggers , AICP , Arrow 
```

## Bugs on unofficial build
```
No
```

## How long have you been building for?
```
2 Weeks / 6 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
AllForrOne 
```

**Comment by afterallafk** [comment]
Your trees looks good. No issues from my side but I can see that you are doing buildbotting by building so many roms.
Also you are very new to this and have very less contributions.

**Comment by Dhruvesh16** [comment]
I have messaged you on telegram once check

**Comment by Dhruvesh16** [comment]
You are accepted as you have answered questions.
