### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jaymistry258** [ProjectBlaze/maintainership#48]
## Device you want to apply for
```
Poco X2 / Redmi K30 (phoenix)
```

## Device tree sources

```
https://github.com/jaymistry258/device_xiaomi_phoenix.git
https://github.com/jaymistry258/kernel_xiaomi_phoenix.git
https://github.com/jaymistry258/vendor_xiaomi_phoenix.git
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Poco_X2_Builds
```

## Other ROM's you maintain officially or unofficially
```
Project-Xtended (Officially)
EvolutionX, BananDroid, AlphaDroid, PixelExperiencePlus, OctaviOS, PixelExtended, CherishOS (Unofficially)
```

## Bugs on unofficial build
```
QS Lag, Weird Apps not showing in PS, Google NGA not work (All Mentioned bugs are Rom Specific not facing this bugs on all roms)
```

## How long have you been building for?
```
2 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
jaymistry258
```

**Comment by afterallafk** [comment]
Why building so much roms even though u have one official ?

**Comment by jaymistry258** [comment]
because my self and users like different flavors and everyone's choice is different so i'm doing all builds if it possible to build by me and also I'm getting high end servers free so why not fulfill some joy :)

**Comment by omnitrix21** [comment]
also, authorship are not properly given, https://github.com/jaymistry258/device_xiaomi_phoenix/commit/7becc00cac49608e1f3e236a1b7eee10e464874e 
also , in this commit https://github.com/jaymistry258/device_xiaomi_phoenix/commit/755348705bc7d220e43ec76ed52a9601de0d6fb6 authorship is not properly given to neobuddy 
https://github.com/SOVIET-ANDROID/device_xiaomi_raphael/commit/808270aba7f06b20449eecf912c1c6579aca6d13

**Comment by omnitrix21** [comment]
@omnitrix21 lol he kanged some commits too

**Comment by jaymistry258** [comment]
okay just check after 30min i will add credits to respected owners

**Comment by jaymistry258** [comment]
how's sounds ?

**Comment by afterallafk** [comment]
> because my self and users like different flavors and everyone's choice is different so i'm doing all builds if it possible to build by me and also I'm getting high end servers free so why not fulfill some joy :)

even though if would have got high servers then also I would have not builded becoz i know building 69 roms and then people start calling buildbot and then no one accepts also.

**Comment by afterallafk** [comment]
And u never built blaze unofficial also and still applying here?

**Comment by jaymistry258** [comment]
People who calling others buildbot is arrogant in eye so its up to you what do you think about me :)
I'm just going to build right now that's why i asked if you want one unofficial build then no problem i can also give that :)

**Comment by afterallafk** [comment]
> People who calling others buildbot is arrogant in eye so its up to you what do you think about me :) I'm just going to build right now that's why i asked if you want one unofficial build then no problem i can also give that :)

If you want to be in the team stop building those many unofficials and fix some of the authorships and max 3 roms are allowed per maintainer. That's it if you can manage to control yourself from building so many unofficial then we can think.

**Comment by jaymistry258** [comment]
Agree on your offer now ??

**Comment by jaymistry258** [comment]
Concerned Credits given to the respected owners please review it.

**Comment by afterallafk** [comment]
> Agree on your offer now ??

this is not an offer that are terms and conditions.

**Comment by jaymistry258** [comment]
okay sir I'm agree with your Terms and Conditions.

**Comment by omnitrix21** [comment]
fix your commits history or --amend them.
better luck next time, thanks
