### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by jaymistry258** [ProjectBlaze/maintainership#49]
## Device you want to apply for
```
Xiaomi Redmi K30 / Poco X2
```

## Device tree sources

```
https://github.com/jaymistry258/device_xiaomi_phoenix
https://github.com/jaymistry258/kernel_xiaomi_phoenix
https://github.com/jaymistry258/vendor_xiaomi_phoenix
```

## Link to the platform where you have released your unofficial build
```
https://t.me/Poco_X2_Builds
```

## Other ROM's you maintain officially or unofficially
```
Evolution X, Xtended, Blaze
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
3 Months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
jaymistry258
```

**Comment by omnitrix21** [comment]
@jaymistry258 hmm letme check

**Comment by rockstar5495** [comment]
https://github.com/jaymistry258/device_xiaomi_phoenix/commit/0eceb0038293de2ca85a71fe682aa26cbbc01250
from where you imported compatibility matrix

**Comment by jaymistry258** [comment]
i have google it and found all matrix then i have combined it together according to my requirements and then i added in my repository.

**Comment by rockstar5495** [comment]
i don't think so either you copied from somewhere or picked from some other device as it has dolby which should come with Dolby commit

**Comment by rockstar5495** [comment]
i am into custom ROM development since 2019 and now I know this much that which commit is for which and from where it comes.

**Comment by jaymistry258** [comment]
If you really think that i have copied someones commit okay then god father of custom roms find me out in the whole github same to same commit like me and i wll leave custom rom devlopment forever.

I already mentioned that i have googled it and i found reference and i combined together and added in my repo.

😑

**Comment by rockstar5495** [comment]
instead of all this just rebase your trees and add dolby entry from compatibility matrix to following commit 
https://github.com/jaymistry258/device_xiaomi_phoenix/commit/2e3d609394df48f1f4d2de9463d4dd289fcc43b1

**Comment by rockstar5495** [comment]
https://github.com/rockstar5495/android_device_xiaomi_raphael/commit/d391b5bebe3cde373c93eefd7bc624cdc8873b8e
see this commit

**Comment by jaymistry258** [comment]
Please review my device tree again with blaze branch i have rebased my DT as per your suggestion if anything still wrong let me know.

**Comment by rockstar5495** [comment]
It seems fine now will let you know after discussing with team

**Comment by khirendra03** [comment]
@rockstar5495 @afterallafk don't accept him right now

**Comment by jaymistry258** [comment]
> @rockstar5495 @afterallafk don't accept him right now

Mention reason for not accept 😑

**Comment by afterallafk** [comment]
> > @rockstar5495 @afterallafk don't accept him right now
> 
> Mention reason for not accept expressionless

Wait for final acceptance

**Comment by BasharatKar** [comment]
@jaymistry258 you have very less contribution in the the dt

**Comment by jaymistry258** [comment]
now I'm not interested anymore.

**Comment by omnitrix21** [comment]
@jaymistry258 Maintainership reviews takes time. If you wish to revoke then ok
