### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by YuvrajMehta** [ProjectBlaze/maintainership#50]
## Device you want to apply for
``` Xiaomi 11x Pro
Your device name and codename
``` Haydn

## Device tree sources
<!--
* Must be public on GitHub/GitLab
* Must add kernel and vendor as well
* Authorship should be proper
* Add common trees if applicable
-->
```
https://github.com/YuvrajMehta/android_device_xiaomi_haydn
https://github.com/YuvrajMehta/android_device_xiaomi_sm8350-common
https://github.com/YuvrajMehta/android_kernel_qcom_sm8350
https://github.com/YuvrajMehta/proprietary_vendor_xiaomi_haydn
https://github.com/YuvrajMehta/proprietary_vendor_xiaomi_sm8350-common
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Insert here
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
10 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

## Contact
### Telegram username
```
t.me/YuvrajMehta
```

**Comment by afterallafk** [comment]
Please fill the building experience time period.

**Comment by afterallafk** [comment]
Trees are proper , +1 from my side

**Comment by afterallafk** [comment]
Accepted 👍

**Comment by rockstar5495** [comment]
https://github.com/YuvrajMehta/android_device_xiaomi_sm8350-common/commit/929bab58eb2629e41c4ddefe10f5bd8bcdf23001

Fix this commit Airtel doesn't support VoNR being NSA infrastructure

**Comment by YuvrajMehta** [comment]
okay
