### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by itsxrp** [ProjectBlaze/maintainership#52]
## Device you want to apply for
```
realme GT Master aka lunaa
```

## Device tree sources

```
https://github.com/itsxrp/android_device_realme_lunaa.git
https://github.com/itsxrp/android_device_oneplus_sm8350-common.git
https://github.com/itsxrp/kernel_oneplus_sm8350.git (topaz branch)
```

## Link to the platform where you have released your unofficial build
```
https://t.me/xrpbuilds
```

## Other ROM's you maintain officially or unofficially
```
PixelOS Official
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 Years +
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
itsXRP
```

**Comment by omnitrix21** [comment]
accepted 👍 
our team will contact you soon
