### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by shravansayz** [ProjectBlaze/maintainership#53]
## Device you want to apply for
```
Realme X (RMX1901)
```

## Device tree sources

```
https://github.com/shravansayz/device_realme_RMX1901
https://github.com/shravansayz/kernel_realme_sdm710
https://github.com/shravansayz/vendor_realme_RMX1901
```

## Link to the platform where you have released your unofficial build
```
https://t.me/rmx1901x
```

## Other ROM's you maintain officially or unofficially
```
unofficially
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
https://t.me/shrav_1
```

**Comment by afterallafk** [comment]
https://github.com/shravansayz/device_realme_RMX1901/commit/30f3e0c3b6c8740840f3c88e3388a8f575995269
https://github.com/shravansayz/device_realme_RMX1901/commit/9f757a7b5f3e3cad7362217535001c5e17ed57ed
don't u think these two should merged and why commited them separately?

**Comment by afterallafk** [comment]
Noob Behaviour

**Comment by cat658011** [comment]
> [shravansayz/device_realme_RMX1901@30f3e0c](https://github.com/shravansayz/device_realme_RMX1901/commit/30f3e0c3b6c8740840f3c88e3388a8f575995269) [shravansayz/device_realme_RMX1901@9f757a7](https://github.com/shravansayz/device_realme_RMX1901/commit/9f757a7b5f3e3cad7362217535001c5e17ed57ed) don't u think these two should merged and why commited them separately?

noob in git

**Comment by afterallafk** [comment]
> > [shravansayz/device_realme_RMX1901@30f3e0c](https://github.com/shravansayz/device_realme_RMX1901/commit/30f3e0c3b6c8740840f3c88e3388a8f575995269) [shravansayz/device_realme_RMX1901@9f757a7](https://github.com/shravansayz/device_realme_RMX1901/commit/9f757a7b5f3e3cad7362217535001c5e17ed57ed) don't u think these two should merged and why commited them separately?
> 
> noob in git

ofc true
