### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by CYB3R0ID694** [ProjectBlaze/maintainership#54]
## Device you want to apply for
```
Pixel 6a Bluejay
```

## Device tree sources

```
https://github.com/CYB3R0ID694/android_device_google_bluejay
https://android.googlesource.com/device/google/bluejay-kernel.git
https://github.com/TheMuppets/proprietary_vendor_google_bluejay
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Nothing
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 & half year
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes as It's easy to use & maintained by Google itself.
```

### Telegram username
```
CYB3R0ID694
```

**Comment by CYB3R0ID694** [comment]
XDA Thread uploaded

https://xdaforums.com/t/rom-14-unofficial-stable-projectblaze-bluejay-30-04-2024.4669517/

**Comment by afterallafk** [comment]
> XDA Thread uploaded
> 
> https://xdaforums.com/t/rom-14-unofficial-stable-projectblaze-bluejay-30-04-2024.4669517/

ok

**Comment by afterallafk** [comment]
Accepted
