### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by CarlosPriQue** [ProjectBlaze/maintainership#55]
## Device you want to apply for
```
Redmi Note 13 Pro 5G (Garnet)
```

## Device tree sources

```
https://github.com/CarlosPriQue/device_xiaomi_garnet
https://github.com/CarlosPriQue/device_xiaomi_garnet-prebuilt
https://github.com/CarlosPriQue/vendor_xiaomi_garnet
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Official CherishOS on Mi9T (Davinci)
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
Years
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
Yes. Code not released or incomplete!
```

### Telegram username
```
@PriQue77
```

**Comment by afterallafk** [comment]
Accepted already
