### ISSUE TITLE
New maintainer - Realme GT2 posrche

### ISSUE THREAD

**Issue by kaushikradheytv** [ProjectBlaze/maintainership#56]
## Device you want to apply for

Realme GT2 (posrche)

Realme GT2 - posrche

## Device tree sources

https://github.com/kaushikradheytv/device_realme_porsche/tree/fourteen
https://github.com/kaushikradheytv/device_oneplus_sm8350-common
https://github.com/kaushikradheytv/vendor_realme_porsche
https://github.com/kaushikradheytv/vendor_oneplus_sm8350-common
https://github.com/kaushikradheytv/hardware_oplus
https://github.com/kaushikradheytv/kernel_oneplus_sm8350

## Link to the platform where you have released your unofficial build

Telegram: https://t.me/RealmeGT2_Updates

## Other ROM's you maintain officially or unofficially
``` 
No Other Rom
```

## Bugs on unofficial build
```
None Since last month 3.6 version, 3.7 is stable only launcher is buggy
```

## How long have you been building for?
```
Weeks/Months/Years
```
3 Months

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
Mister x

Your Telegram username
https://t.me/rs_kaushik

**Comment by afterallafk** [comment]
Where are your trees?

**Comment by afterallafk** [comment]
These are whyredfire trees !

**Comment by kaushikradheytv** [comment]
@afterallafk Hi, I have added the forked trees. Thanks for bringing the awesome ROM to us. I look forward to seeing you on Android 15.

**Comment by afterallafk** [comment]
> @afterallafk Hi, I have added the forked trees. Thanks for bringing the awesome ROM to us. I look forward to seeing you on Android 15.

Bringup is not proper learn the git that how to use it from the commandline

**Comment by Dhruvesh16** [comment]
Learn git and bringup trees in proper way then re-apply.
