### ISSUE TITLE
New maintainer - realme GT2 (Porsche)

### ISSUE THREAD

**Issue by MISTERXZONE** [ProjectBlaze/maintainership#57]
## Device

Realme GT2 Porsche

## Device tree sources

Device: https://github.com/MISTERXZONE/device_realme_porsche
Vendor: https://github.com/MISTERXZONE/vendor_realme_porsche
Device Common: https://github.com/MISTERXZONE/device_oneplus_sm8350-common
Kernel: https://github.com/MISTERXZONE/kernel_oneplus_sm8350_gato

## Link to the platform where you have released your unofficial build
Telegram: https://t.me/RealmeGT2_Official

## Other ROM's you maintain officially or unofficially

No

## Bugs on unofficial build

None

## How long have you been building for?

3 Months

## SELinux status?

Enforcing.

## Are you using a prebuilt kernel? If yes, why?

No.

### Telegram username

Mister X: https://t.me/mister_xrs

**Comment by afterallafk** [comment]
Learn git

**Comment by Dhruvesh16** [comment]
Learn git properly and re-apply.
