### ISSUE TITLE
New maintainer for sweet

### ISSUE THREAD

**Issue by Musafir02** [ProjectBlaze/maintainership#58]
## Device you want to apply for Redmi note 10 pro 
```
Your device name and codename sweet/sweetin
```

## Device tree sources

```
https://github.com/Musafir02/device_xiaomi_sweet.git
https://github.com/Musafir02/kernel_xiaomi_sm6150.git
https://github.com/Musafir02/vendor_xiaomi_sweet.git
```

## Link to the platform where you have released your unofficial build
```
Insert here
https://t.me/RoyalOSsweet/98
https://t.me/RoyalOSsweet/90
```

## Other ROM's you maintain officially or unofficially
```
Insert here
https://t.me/RoyalOSsweet/98
https://t.me/RoyalOSsweet/90
```

## Bugs on unofficial build
```
Camera issue but I fixed it.
```

## How long have you been building for?
```
1 month 
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Musafir1875
```

**Comment by shoya0x00** [comment]
Answer few questions 

1. Where is the common trees?
2. Where is the blaze bringup?

**Comment by Musafir02** [comment]
https://github.com/Musafir02/device_xiaomi_sm6150-common.git
https://github.com/Musafir02/vendor_xiaomi_sm6150-common.git

Now I am working on blaze unofficial build if you make me maintainer then I will release official build asap

**Comment by shoya0x00** [comment]
> Now I am working on blaze unofficial build if you make me maintainer then I will release official build asap

where is your bringup for blaze? i don't see it anywhere

**Comment by Musafir02** [comment]
Today I will do it

**Comment by shoya0x00** [comment]
sorry we can't approve your maintainership request. i have checked your trees. i don't see any device side contribution. also no bringup, all you did is take device tree from pixelage and call it a day.
