### ISSUE TITLE
Juice maintainer

### ISSUE THREAD

**Issue by lynnnnzx** [ProjectBlaze/maintainership#6]
## Device you want to apply for
```
Poco M3 / Xiaomi Redmi 9T / Redmi 9 Power And Redmi Note 9 4G (Codename: juice)
```

## Device tree sources
```
https://github.com/lynnnnzx/device_xiaomi_juice
https://github.com/lynnnnzx/vendor_xiaomi_juice
https://github.com/lynnnnzx/kernel_xiaomi_juice
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
PixelPlusUI Official Juice
```

## Bugs on unofficial build
```
Nothing
```

## How long have you been building for?
```
Monthly
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@hakazeee
```

**Comment by BasharatKar** [comment]
Have you built unofficial build and successfully booted without bugs?

**Comment by BasharatKar** [comment]
Ok Welcome To Project Blaze
