### ISSUE TITLE
New maintainer for Lavender

### ISSUE THREAD

**Issue by c0pt4n** [ProjectBlaze/maintainership#7]
## Device you want to apply for
```
Redmi Note 7 (Lavender)
```

## Device tree sources

```
https://github.com/OmarAlCoptan/device_xiaomi_lavender
https://github.com/OmarAlCoptan/device_xiaomi_sdm660
https://github.com/OmarAlCoptan/vendor_xiaomi_lavender-common
https://github.com/OmarAlCoptan/vendor_xiaomi_sdm660-common
https://github.com/ArrowOS-Devices/android_kernel_xiaomi_sdm660
```

## Link to the platform where you have released your unofficial build
```
Didn't release as the instructions said
```

## Other ROM's you maintain officially or unofficially
```
Nusantara + PixelOS unofficials
```

## Bugs on unofficial build
```
Night Light only
```

## How long have you been building for?
```
2/5/0
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@AlCoptan99
```

**Comment by afterallafk** [comment]
> 

I can't see your common trees as it is not opening

**Comment by c0pt4n** [comment]
> > 
> 
> I can't see your common trees as it is not opening

How sir? btw try again it is its link

https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common

**Comment by afterallafk** [comment]
> > > 
> > 
> > 
> > I can't see your common trees as it is not opening
> 
> How sir? btw try again it is its link
> 
> https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common

https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05 this is bad fix you should remove this

**Comment by c0pt4n** [comment]
> > > > 
> > > 
> > > 
> > > I can't see your common trees as it is not opening
> > 
> > 
> > How sir? btw try again it is its link
> > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> 
> [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this

Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP).
 BTW , if your advice to remove I will do

**Comment by ghost** [comment]
What server u own? @OmarAlCoptan

**Comment by afterallafk** [comment]
> > > > > 
> > > > 
> > > > 
> > > > I can't see your common trees as it is not opening
> > > 
> > > 
> > > How sir? btw try again it is its link
> > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > 
> > 
> > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> 
> Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do

is there any issue in unofficial recovery?

**Comment by c0pt4n** [comment]
> What server u own?

I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr 


and these are some of my builds on it

https://cirrus-ci.com/build/6108387636150272

https://cirrus-ci.com/build/5660897971535872

https://cirrus-ci.com/task/5323407091826688

https://cirrus-ci.com/build/6717932574081024

https://cirrus-ci.com/task/6264235448598528

https://cirrus-ci.com/task/4548528151199744

https://cirrus-ci.com/build/5367063387570176

https://cirrus-ci.com/task/6495448906072064

**Comment by afterallafk** [comment]
> > What server u own?
> 
> I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> 
> and these are some of my builds on it
> 
> https://cirrus-ci.com/build/6108387636150272
> 
> https://cirrus-ci.com/build/5660897971535872
> 
> https://cirrus-ci.com/task/5323407091826688
> 
> https://cirrus-ci.com/build/6717932574081024
> 
> https://cirrus-ci.com/task/6264235448598528
> 
> https://cirrus-ci.com/task/4548528151199744
> 
> https://cirrus-ci.com/build/5367063387570176
> 
> https://cirrus-ci.com/task/6495448906072064

Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers

**Comment by c0pt4n** [comment]
> > > What server u own?
> > 
> > 
> > I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> > and these are some of my builds on it
> > https://cirrus-ci.com/build/6108387636150272
> > https://cirrus-ci.com/build/5660897971535872
> > https://cirrus-ci.com/task/5323407091826688
> > https://cirrus-ci.com/build/6717932574081024
> > https://cirrus-ci.com/task/6264235448598528
> > https://cirrus-ci.com/task/4548528151199744
> > https://cirrus-ci.com/build/5367063387570176
> > https://cirrus-ci.com/task/6495448906072064
> 
> Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers

Even if ROM builders supported OTA?

**Comment by afterallafk** [comment]
> > > > What server u own?
> > > 
> > > 
> > > I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> > > and these are some of my builds on it
> > > https://cirrus-ci.com/build/6108387636150272
> > > https://cirrus-ci.com/build/5660897971535872
> > > https://cirrus-ci.com/task/5323407091826688
> > > https://cirrus-ci.com/build/6717932574081024
> > > https://cirrus-ci.com/task/6264235448598528
> > > https://cirrus-ci.com/task/4548528151199744
> > > https://cirrus-ci.com/build/5367063387570176
> > > https://cirrus-ci.com/task/6495448906072064
> > 
> > 
> > Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers
> 
> Even if ROM builders supported OTA?

they create conflicts

**Comment by ghost** [comment]
> > > What server u own?
> > 
> > 
> > I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> > and these are some of my builds on it
> > https://cirrus-ci.com/build/6108387636150272
> > https://cirrus-ci.com/build/5660897971535872
> > https://cirrus-ci.com/task/5323407091826688
> > https://cirrus-ci.com/build/6717932574081024
> > https://cirrus-ci.com/task/6264235448598528
> > https://cirrus-ci.com/task/4548528151199744
> > https://cirrus-ci.com/build/5367063387570176
> > https://cirrus-ci.com/task/6495448906072064
> 
> Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers

Rom builders support ota and u can grab json files easily there

**Comment by afterallafk** [comment]
ok I will see how u will do once we start giving ota

> > > > What server u own?
> > > 
> > > 
> > > I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> > > and these are some of my builds on it
> > > https://cirrus-ci.com/build/6108387636150272
> > > https://cirrus-ci.com/build/5660897971535872
> > > https://cirrus-ci.com/task/5323407091826688
> > > https://cirrus-ci.com/build/6717932574081024
> > > https://cirrus-ci.com/task/6264235448598528
> > > https://cirrus-ci.com/task/4548528151199744
> > > https://cirrus-ci.com/build/5367063387570176
> > > https://cirrus-ci.com/task/6495448906072064
> > 
> > 
> > Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers
> 
> Rom builders support ota and u can grab json files easily there

**Comment by c0pt4n** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > I can't see your common trees as it is not opening
> > > > 
> > > > 
> > > > How sir? btw try again it is its link
> > > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > > 
> > > 
> > > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> > 
> > 
> > Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do
> 
> is there any issue in unofficial recovery?

Not much people love TWRP

**Comment by c0pt4n** [comment]
> ok I will see how u will do once we start giving ota
> 
> > > > > What server u own?
> > > > 
> > > > 
> > > > I use ROM-Builders repo , if the queue is fine , it builds the rom in 1 hr
> > > > and these are some of my builds on it
> > > > https://cirrus-ci.com/build/6108387636150272
> > > > https://cirrus-ci.com/build/5660897971535872
> > > > https://cirrus-ci.com/task/5323407091826688
> > > > https://cirrus-ci.com/build/6717932574081024
> > > > https://cirrus-ci.com/task/6264235448598528
> > > > https://cirrus-ci.com/task/4548528151199744
> > > > https://cirrus-ci.com/build/5367063387570176
> > > > https://cirrus-ci.com/task/6495448906072064
> > > 
> > > 
> > > Till we don't have ota support u can use roms builders, but once we bring OTA support u must switch to some other servers
> > 
> > 
> > Rom builders support ota and u can grab json files easily there

OK

**Comment by afterallafk** [comment]
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > I can't see your common trees as it is not opening
> > > > > 
> > > > > 
> > > > > How sir? btw try again it is its link
> > > > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > > > 
> > > > 
> > > > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> > > 
> > > 
> > > Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do
> > 
> > 
> > is there any issue in unofficial recovery?
> 
> Not much people love TWRP

okay then leave that commit as it is

**Comment by c0pt4n** [comment]
> > > > > > > > 
> > > > > > > 
> > > > > > > 
> > > > > > > I can't see your common trees as it is not opening
> > > > > > 
> > > > > > 
> > > > > > How sir? btw try again it is its link
> > > > > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > > > > 
> > > > > 
> > > > > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> > > > 
> > > > 
> > > > Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do
> > > 
> > > 
> > > is there any issue in unofficial recovery?
> > 
> > 
> > Not much people love TWRP
> 
> okay then leave that commit as it is

Okay sir , I tried it on Nusa and PixelOS and no problems

**Comment by afterallafk** [comment]
> > > > > > > > > 
> > > > > > > > 
> > > > > > > > 
> > > > > > > > I can't see your common trees as it is not opening
> > > > > > > 
> > > > > > > 
> > > > > > > How sir? btw try again it is its link
> > > > > > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > > > > > 
> > > > > > 
> > > > > > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> > > > > 
> > > > > 
> > > > > Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do
> > > > 
> > > > 
> > > > is there any issue in unofficial recovery?
> > > 
> > > 
> > > Not much people love TWRP
> > 
> > 
> > okay then leave that commit as it is
> 
> Okay sir , I tried it on Nusa and PixelOS and no problems

Okay No problem , U r selected ur trees seem fine to me

**Comment by thefaizanbashir** [comment]
@OmarAlCoptan what's the need of adding Gapps flag? https://github.com/OmarAlCoptan/device_xiaomi_lavender/commit/d5769c7474c3b29c48fc377a2bc38a8ee52145fa

**Comment by c0pt4n** [comment]
> > > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > 
> > > > > > > > > I can't see your common trees as it is not opening
> > > > > > > > 
> > > > > > > > 
> > > > > > > > How sir? btw try again it is its link
> > > > > > > > https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common
> > > > > > > 
> > > > > > > 
> > > > > > > [OmarAlCoptan/device_xiaomi_sdm660-common@ab3dc50](https://github.com/OmarAlCoptan/device_xiaomi_sdm660-common/commit/ab3dc501943c0e0a29258a7d87bb91ca87ca4b05) this is bad fix you should remove this
> > > > > > 
> > > > > > 
> > > > > > Without it , if there is SdCard inserted the recovery gets stuck on recovery logo (OrangeFox) , people should change the recovery into unofficial one(TWRP). BTW , if your advice to remove I will do
> > > > > 
> > > > > 
> > > > > is there any issue in unofficial recovery?
> > > > 
> > > > 
> > > > Not much people love TWRP
> > > 
> > > 
> > > okay then leave that commit as it is
> > 
> > 
> > Okay sir , I tried it on Nusa and PixelOS and no problems
> 
> Okay No problem , U r selected ur trees seem fine to me

Nice bro
