### ISSUE TITLE
New maintainer

### ISSUE THREAD

**Issue by AkashHalder520** [ProjectBlaze/maintainership#8]
## Device you want to apply for
```
POCO M2 PRO and MIATOLL
```

## Device tree sources

```
https://github.com/AkashHalder520/device_xiaomi_miatoll/tree/blaze
https://github.com/AkashHalder520/device_xiaomi_sm6250-common
https://github.com/AkashHalder520/android_kernel_xiaomi_sm6250
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_miatoll
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_miatoll-gcam
https://gitlab.pixelexperience.org/android/vendor-blobs/vendor_xiaomi_sm6250-common
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
PIXEL EXTENDED MIATOLL
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
2 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```akashhalder520```

**Comment by BasharatKar** [comment]
I have checked your trees so can you tell do you have basic knowledge about github? Like cherry picking and authorships?

**Comment by AkashHalder520** [comment]
yes for cherry picking 
git remote add 'branch' (the branch from you want to pick) 'repo link'
git fetch 'branch'
git cherry-pick 'commit_code'
-Fix conflicts by git status , use (git add) after fixing conflicts
git cherry-pick --continue
git push in branch	
authorships-->
git commit--amend --author "username <email>"

**Comment by BasharatKar** [comment]
Ok fine will contact u when we finish reviewing
