### ISSUE TITLE
New maintainer for mido

### ISSUE THREAD

**Issue by focaccia-pie** [ProjectBlaze/maintainership#9]
## Device you want to apply for
```
Redmi note 4x
```

## Device tree sources

```
https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido
https://github.com/anyinglulu1/android_kernel_xiaomi_mido
https://github.com/anyinglulu1/proprietary_vendor_xiaomi
```

## Link to the platform where you have released your unofficial build
```
Insert here
```

## Other ROM's you maintain officially or unofficially
```
Crdroid and awaken unofficial
```

## Bugs on unofficial build
```
None
```

## How long have you been building for?
```
8-9 months
```

## SELinux status?
```
Enforcing.
```

## Are you using a prebuilt kernel? If yes, why?
```
No.
```

### Telegram username
```
@Anyinglulu1
```

**Comment by BasharatKar** [comment]
Alright trees looks fine wait sometime.

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> ```
> Redmi note 4x
> ```
> 
> ## Device tree sources
> ```
> https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido
> https://github.com/anyinglulu1/android_kernel_xiaomi_mido
> https://github.com/anyinglulu1/proprietary_vendor_xiaomi
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> Insert here
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> Crdroid and awaken unofficial
> ```
> 
> ## Bugs on unofficial build
> ```
> None
> ```
> 
> ## How long have you been building for?
> ```
> 8-9 months
> ```
> 
> ## SELinux status?
> ```
> Enforcing.
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> ```
> @Anyinglulu1
> ```

https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/90885b747ff0c5f0ec2f9e68bee0302cead98a05  beside this commit why other commits are done for same thing can u explain and u reverted that commit than with the name of fix duplicate?

https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/90885b747ff0c5f0ec2f9e68bee0302cead98a05   this and other 
https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/ca684669a29a1d530383115a71973462272bc093 this

**Comment by afterallafk** [comment]
> ## Device you want to apply for
> ```
> Redmi note 4x
> ```
> 
> ## Device tree sources
> ```
> https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido
> https://github.com/anyinglulu1/android_kernel_xiaomi_mido
> https://github.com/anyinglulu1/proprietary_vendor_xiaomi
> ```
> 
> ## Link to the platform where you have released your unofficial build
> ```
> Insert here
> ```
> 
> ## Other ROM's you maintain officially or unofficially
> ```
> Crdroid and awaken unofficial
> ```
> 
> ## Bugs on unofficial build
> ```
> None
> ```
> 
> ## How long have you been building for?
> ```
> 8-9 months
> ```
> 
> ## SELinux status?
> ```
> Enforcing.
> ```
> 
> ## Are you using a prebuilt kernel? If yes, why?
> ```
> No.
> ```
> 
> ## Contact
> ### Telegram username
> ```
> @Anyinglulu1
> ```

what is this messed up commit https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/1caad5090ce9ab52ea490591db81b9fb4c54080e

**Comment by focaccia-pie** [comment]
> > ## Device you want to apply for
> > ```
> > Redmi note 4x
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Device tree sources
> > ```
> > https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido
> > https://github.com/anyinglulu1/android_kernel_xiaomi_mido
> > https://github.com/anyinglulu1/proprietary_vendor_xiaomi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Link to the platform where you have released your unofficial build
> > ```
> > Insert here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Other ROM's you maintain officially or unofficially
> > ```
> > Crdroid and awaken unofficial
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Bugs on unofficial build
> > ```
> > None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## How long have you been building for?
> > ```
> > 8-9 months
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## SELinux status?
> > ```
> > Enforcing.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Are you using a prebuilt kernel? If yes, why?
> > ```
> > No.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Contact
> > ### Telegram username
> > ```
> > @Anyinglulu1
> > ```
> 
> [Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido@90885b7](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/90885b747ff0c5f0ec2f9e68bee0302cead98a05) beside this commit why other commits are done for same thing can u explain and u reverted that commit than with the name of fix duplicate?
> 
> [Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido@90885b7](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/90885b747ff0c5f0ec2f9e68bee0302cead98a05) this and other [Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido@ca68466](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/ca684669a29a1d530383115a71973462272bc093) this

Yeah when I look again the commit I see the are already there in the file and then erase the line , I forget that you can revert that commit, I will not make that mistake again

**Comment by focaccia-pie** [comment]
> > ## Device you want to apply for
> > ```
> > Redmi note 4x
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Device tree sources
> > ```
> > https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido
> > https://github.com/anyinglulu1/android_kernel_xiaomi_mido
> > https://github.com/anyinglulu1/proprietary_vendor_xiaomi
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Link to the platform where you have released your unofficial build
> > ```
> > Insert here
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Other ROM's you maintain officially or unofficially
> > ```
> > Crdroid and awaken unofficial
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Bugs on unofficial build
> > ```
> > None
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## How long have you been building for?
> > ```
> > 8-9 months
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## SELinux status?
> > ```
> > Enforcing.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Are you using a prebuilt kernel? If yes, why?
> > ```
> > No.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ## Contact
> > ### Telegram username
> > ```
> > @Anyinglulu1
> > ```
> 
> what is this messed up commit [Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido@1caad50](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/1caad5090ce9ab52ea490591db81b9fb4c54080e)

I forget to fix conflict

**Comment by rockstar5495** [comment]
Sorry to say but your device tree are heavily messed up and some commits don't have proper authorship also we have maintainer for mido already.

**Comment by khirendra03** [comment]
You should also know how to fix your git history too.

**Comment by focaccia-pie** [comment]
Oh ok thank you

**Comment by khirendra03** [comment]
You have 5 conflict commits.
Look 
- [1](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/1caad5090ce9ab52ea490591db81b9fb4c54080e)
- [2](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/5c8e42d93d3be0b5d9dec5ea58f6f59b94754e2f)
- [3](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/332bbdebaa2013a7d8054966a6500cc71e845c85)
- [4](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/1d989cd49d47f7d82691528a017533e1374bb50b)
- [5](https://github.com/Anyinglulu1-Mido-DeviceTree/android_device_xiaomi_mido/commit/a27a7d59084747b3dddf41bee059e1602e00a1c4)

**Comment by BasharatKar** [comment]
@khirendra03 we have already closed the issue
